from enum import IntEnum

class ErrorCode(IntEnum):
    ERR_SERVER_ERROR = 0
    ERR_INVALID_VALUE = 1
    ERR_INCORRECT_USER = 2
    ERR_MISSING_PARAMETER = 3
    ERR_PERMISSION_INSUFFICIENT = 4
    ERR_OCCUPIED_USERNAME = 5
    ERR_OCCUPIED_SLOT = 6
    ERR_UNALLOCATED_SLOT = 7
    ERR_NO_SECRET_SPECIFIED = 8
    ERR_SECRET_MISMATCH = 9
    ERR_LOCKED_SESSION = 10
    ERR_UNLOCKED_SESSION = 11
    ERR_USER_EXISTS = 12
    ERR_USER_INVALID = 13
    ERR_NO_SIGNATURE_SPECIFIED = 14
    ERR_SIGNATURE_MISMATCH = 15
    ERR_NO_HANDLER = 16
    ERR_SAME_DATATYPE = 17
    ERR_INVALID_SLOT = 18
    ERR_NO_FACE_DETECTED = 19